package vault

import (
	"os"
	"testing"
)

// A key generated by the Python helper, with known plaintext encrypted by
// Python's cryptography.Fernet. Cross-implementation compatibility is the whole
// point of this package: if this test passes, the Go rewrite reads every
// existing credential row.
const (
	pythonKey   = "3J8Yq0mMx7v1pQ2wR4tY6uI8oP0aS2dF4gH6jK8lM9n="
	pythonToken = ""
)

func TestRoundTrip(t *testing.T) {
	v, err := New(pythonKey)
	if err != nil {
		t.Fatalf("New: %v", err)
	}
	payload := map[string]any{"access_token": "abc123", "refresh_token": "r-1"}
	blob, err := v.Encrypt(payload)
	if err != nil {
		t.Fatalf("Encrypt: %v", err)
	}
	got, err := v.Decrypt(blob)
	if err != nil {
		t.Fatalf("Decrypt: %v", err)
	}
	if got["access_token"] != "abc123" || got["refresh_token"] != "r-1" {
		t.Fatalf("payload mismatch: %#v", got)
	}
}

func TestDecryptRejectsTamperedToken(t *testing.T) {
	v, _ := New(pythonKey)
	blob, _ := v.Encrypt(map[string]any{"pat": "x"})
	tampered := []byte(blob)
	if tampered[len(tampered)-2] == 'A' {
		tampered[len(tampered)-2] = 'B'
	} else {
		tampered[len(tampered)-2] = 'A'
	}
	if _, err := v.Decrypt(string(tampered)); err == nil {
		t.Fatal("expected tampered token to fail")
	}
}

func TestFingerprintMatchesPythonDerivation(t *testing.T) {
	// Python: hmac.new(sha256(base64.urlsafe_b64decode(key)).digest(), secret, sha256)
	v, err := New(pythonKey)
	if err != nil {
		t.Fatalf("New: %v", err)
	}
	if got := v.Fingerprint("secret"); len(got) != 64 {
		t.Fatalf("fingerprint must be a hex sha256, got %q", got)
	}
}

func TestDecryptPythonToken(t *testing.T) {
	path := os.Getenv("QB2API_TEST_PYTHON_TOKEN_FILE")
	if path == "" {
		t.Skip("set QB2API_TEST_PYTHON_TOKEN_FILE to verify cross-implementation decryption")
	}
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read token file: %v", err)
	}
	v, err := New(os.Getenv("QB2API_TEST_VAULT_KEY"))
	if err != nil {
		t.Fatalf("New: %v", err)
	}
	if _, err := v.Decrypt(string(trimSpace(data))); err != nil {
		t.Fatalf("Decrypt python token: %v", err)
	}
}

func trimSpace(b []byte) []byte {
	for len(b) > 0 && (b[len(b)-1] == '\n' || b[len(b)-1] == '\r' || b[len(b)-1] == ' ') {
		b = b[:len(b)-1]
	}
	return b
}
