const statusLabels: Record<string, string> = {
  active: "正常",
  action_required: "需要处理",
  already_checked_in: "今日已完成",
  claimed: "已签到",
  cancelled: "已取消",
  disabled: "已停用",
  effective: "已生效",
  enabled: "已启用",
  expired: "已过期",
  expiring: "即将过期",
  failed: "失败",
  finished: "已结束",
  fresh: "最新",
  healthy: "运行正常",
  needs_reauth: "需要重新授权",
  no_expiry: "无到期时间",
  qoder_checkin_disabled: "Qoder 签到活动已关闭",
  qoder_checkin_reauth_required: "签到凭据已失效",
  pending: "待处理",
  rejected: "已拒绝",
  refresh: "可刷新",
  revoked: "已撤销",
  running: "运行中",
  skipped: "已跳过",
  stale: "数据已过期",
  static: "静态凭据",
  starting: "启动中",
  stopped: "已停止",
  stopping: "停止中",
  succeeded: "成功",
  unavailable: "不可用",
  unconfigured: "未配置",
  unknown: "未知",
  valid: "有效",
  verified: "已验证",
  chat: "代理请求",
  checkin: "每日签到",
  manual: "手动触发",
  scheduled: "定时调度",
  verify: "验证",
  env: "环境变量",
  import: "导入",
  oauth: "OAuth 登录",
  not_required: "无需验证",
  unverified: "未验证",
};

export function statusLabel(value: string | boolean | null | undefined): string {
  if (typeof value === "boolean") return value ? "已启用" : "已停用";
  if (value == null || value === "") return "未知";
  return statusLabels[value.toLowerCase()] ?? value;
}
